---
- name: Create a user test
  hosts: "{{ target_host }}"
  tasks:
    - name: Create a user
      user:
        name: "{{ user_name }}"
        state: present
    - name: Collect approval reason
      debug:
        msg: "Approval reason provided by user: {{ approval_reason }}"
